# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8fb620842e8fb9f7699cbf36a4e035e0d8950cf7e178adde25e7e370bc6f741a6c32d76e8102dca900d4f1e7f5e9b49174bff7453c0abd290d973d8ed68ba342

test:
  secret_key_base: c862bd168331418f041e7147df237129eef55a8cae63a9792e5a5100176015a69bc77176677effb70c3f4b6757249b45eb821ce2dd3bfd365fd0ef443c13dd1b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
